### PR TITLE
Log request response

### PR DESCRIPTION
**Pull request by Neyaz**

### CODE REVIEW

**Comment by Neyaz** [comment]
Yes, sure

**Comment by shvetsovdm** [comment]
@Neyaz cool! Can you start or migrate the work to master branch? Because I am going to close **feature/long-live-thread** branch.

**Comment by Neyaz** [comment]
Closed

**Comment by shvetsovdm** [comment]
in favour https://github.com/shvetsovdm/yabeda-datadog/pull/8

**Pull request closed without merging**
